### ISSUE TITLE
Multi-thread bot connection

### ISSUE THREAD

**Issue by hassanila** [davidmann4/ogar-feeder-bot#220]
The connection is very slow because it's done one by one so why not make it multi thread? You will then get 100 bots in less than 1 minute... Also they're ram and cpu inefficent... It takes 500mb+ ram and 100% cpu 2.4ghz with 100bots.... that's very much....

**Comment by davidmann4** [comment]
currently it is multi threaded - maybe you talking about something else ?

**Comment by hassanila** [comment]
@davidmann4 No, I know it is multithreaded  but why is it so slow it takes 10min to get like 50 bots... And it's not proxy or internet problem.... Also it's very resource heavy...

**Comment by WJKH** [comment]
I believe the name of onboardingTimer should be changed because no one understand it.
Just decrease the value of config.onboardingTimer in the config.js file and you will get bots faster.

The resource issue is because node.js isn't multithreading then if you have one of eight cores is the same as node will use only one then 12.5% = 100% CPU usage. I have made a workaround about it https://github.com/davidmann4/ogar-feeder-bot/issues/133

**Comment by hassanila** [comment]
thx @WJKH IT WORKS!
