### ISSUE TITLE
New Userscript is Blank

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#229]
hello when I tried out your new userscript its just a white screen. Is this just Me ?

**Comment by mbm3** [comment]
me too

**Comment by zeliad-papa** [comment]
me too

**Comment by ghost** [comment]
weird I think something is wrong with the script

**Comment by mbm3** [comment]
maybe agar expose error?

**Comment by gcsoftware** [comment]
It seems to be an issue with expose on chrome. I use Firefox and GreaseMonkey (same thing as TamperMonkey) works fine. If your using Chrome you can get the page to load by pressing enter on the address bar.

Maybe @davidmann4 should remove the hook until expose works properly with chrome?

**Comment by hassanila** [comment]
It's some bullshit, cuz how can a script break just by adding 2 lines of pure working javascript/jquery code?  Very weird...   I don't get it.... But please instead of just downgrading consider finding a fix for Chrome users... check my other issue: https://github.com/davidmann4/ogar-feeder-bot/pull/225#issuecomment-187028983  the console gets full of errors and Agar.io takes 20 secs to load....  @davidmann4 Please assign this issue as a high priority bug.

---

![2016-02-22 07_10_10-](https://cloud.githubusercontent.com/assets/15068696/13242724/334e7004-d9f8-11e5-90d9-53b55cc4dfee.png)
![2016-02-22 07_27_31-agar io](https://cloud.githubusercontent.com/assets/15068696/13242723/334dea1c-d9f8-11e5-8311-7b746ce5ebe7.png)

**Comment by ghost** [comment]
inspecting agario with the script this will say

Uncaught TypeError: str.split is not a function
Uncaught TypeError: window.setGameMode is not a function
Uncaught TypeError: Cannot read property 'hooks' of undefined

**Comment by davidmann4** [comment]
thats why we need more people hopping over to pull requests and test stuff (new features)

**Comment by davidmann4** [comment]
@gcsoftware chrome is the main platform

**Comment by ghost** [comment]
@davidmann4 can u pls fix it :warning:

**Comment by davidmann4** [comment]
for now just take an older version of the userscript: https://github.com/davidmann4/ogar-feeder-bot/commits/6cdb149db26efb281d204253d64fd90f14a48ceb/ogar-feeder-bot.user.js

**Comment by Billyeee** [comment]
![2](https://cloud.githubusercontent.com/assets/17383145/13249137/76a9b13c-da5d-11e5-8400-acd29b17b1d9.png)
change to
![1](https://cloud.githubusercontent.com/assets/17383145/13249136/75cd8b80-da5d-11e5-9a5a-5189f4ea0c11.png)
delete the ''+''

**Comment by davidmann4** [comment]
pull request?

**Comment by davidmann4** [comment]
https://github.com/davidmann4/ogar-feeder-bot/pull/232 please confirm that this will work

**Comment by davidmann4** [comment]
fixed in newest version
