### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by loboere** [davidmann4/ogar-feeder-bot#230]
also place the uuid ,  
however not advancing
![rtyr](https://cloud.githubusercontent.com/assets/15265895/13241566/f5b6ea5a-d9ca-11e5-9758-a3ad90b2684e.PNG)

**Comment by hyuga01** [comment]
same

**Comment by hassanila** [comment]
You have to change uuid and server ip in both userscript and config.js... otherwise you will not get connected.... The server Ip should be 127.0.0.1:8081  if you're hosting it on the same computer that you use to play... if it's another computer then use that computer's ip... Works now?

---

![2016-02-21 18_57_49-greenshot](https://cloud.githubusercontent.com/assets/15068696/13242527/d7be0db4-d9f5-11e5-8a1b-db93d7b746ff.png)
![2016-02-23 06_16_14-agar io](https://cloud.githubusercontent.com/assets/15068696/13242535/e821a684-d9f5-11e5-86cb-8735edbaeaf9.png)
**_Nice**_

**Comment by Dohab** [comment]
I think it's the free agar.io server, maybe they've changed the port or something.

**Comment by hassanila** [comment]
@Dohab No it's not... check for yourself your config.js and userscript to see... I you're running the server on same pc that you play at then the ip adress is 127.0.0.1:8081

**Comment by Dohab** [comment]
@hassanila97 It was working perfectly, I didn't change anything.
Suddenly, it stopped working!

**Comment by hassanila** [comment]
@Dohab do you see your uuid when you go to Agar.io in Chrome? If not then it's an update that broke it, you have to downgrade the userscript...

**Comment by Dohab** [comment]
@hassanila97 Yes, the uuid appears.
Does it still work with you?

**Comment by hassanila** [comment]
yes but with downgraded version

**Comment by Dohab** [comment]
@hassanila97 Hmmmm.
I think I have an older version, I will try.

**Comment by Dohab** [comment]
@hassanila97 Nope, still not working.

**Comment by loboere** [comment]
same 
Suddenly, it stopped working!

**Comment by ghost** [comment]
run the server.js!

With node

**Comment by davidmann4** [comment]
works again

**Comment by Dohab** [comment]
@MinersMC this server.js never worked with me.

@davidmann4 Not yet

**Comment by ghost** [comment]
@Dohab k then :/
