### ISSUE TITLE
This is frustrating 

### ISSUE THREAD

**Issue by Dohab** [davidmann4/ogar-feeder-bot#261]
I have a VPS, with 7 IPs which I "proxified" them, (I know I said that thousand times), and I get like only 3 bots that I have to split or trick them to eat them?
Tell me something, does those IPs count as one which is the main VPS ip?
I don't get it.

Another thing, in the lower right corner, the coordinates are working to the opposite way.
I mean, when I move my mouse up, the bot goes down and so.

**Comment by picusc** [comment]
I need the answer to this question too. I just want to know how raga.pw and agarbots.net are able to get it working ? From where do all this (sometimes 400+) bots come from? Are they using proxies?

**Comment by Dohab** [comment]
Exactly!
I Tried to buy 200 ips from my host company, they told this:

> ARIN is the organization that presides over all IP address provisions in North America. Contrary to popular belief no one provider has the ability to provide you more IP's than any other. With that in mind we have no reason to deny you as many IP's as you would like so long as you do not violate ARIN's policies (most relevant being section 4.2).
> 
> How to provide Justification
> 
> Send an email to us detailing the following:
> 
> Service(s) with which these IPs will be used (please be detailed).
> Number of addresses needed immediately.
> How many addresses you anticipate needing within one year.

And get that @picusc , the cost of 256 ip per month is $190 !!!
Could those be run on a VPS? nooo way, they need a very expensive dedicated server to run, maybe more than one server.

Some proxy providers give you like 1000 proxy per day, I tried one of these ake companies , and I get only like 5 bots.

**Comment by picusc** [comment]
Hmm.. I am not a very technical person. But I think that finding proxies is the not the main issue. The main issue is finding your cell in the minimap. Agario updated yesterday again and now even raga is not working. I think what keeps happening is that agario makes is harder and harder to find the target cell and therefore the bot makers have to work harder and harder too. I say that proxies are not the main issue becaue I am fairly certain that the script is able to connect to the server but it is unable to find the cell.

**Comment by Dohab** [comment]
Well, scrambling cells is a global problem, but no security system is complete as a known fact. people will find a way eventually.
I was taking about how many cells you get from proxies, or raga doesn't use proxies?
You said and I qoute :

> From where do all this (sometimes 400+) bots come from? Are they using proxies?

**Comment by picusc** [comment]
Ok. I did some searching. 

According to [this link](https://archive.is/M5M2B#selection-46975.0-46978.0), Agario limits 5 bots per ip.
According to [this link](https://archive.is/JmlRO#selection-685.0-694.0), Agario limits 3 bots per ip.
According to [this link](https://archive.is/1PwZW#selection-2989.0-2996.0)(most recent), Agario limits 1 bots per ip.

So lets assume that the third link is accurate. In that case, If you want 100 bots, so you will need 100 different ip address.  I think that this can be easily accomplished by using public proxys. You might have to keep filtering out the bad proxy's every few days using a free service like [Online Proxy Checker](http://www.checker.freeproxy.ru/checker/), but it should work.

Now what I do not understand is that if it is this simple, why are all major bot sites limit their bots to a low number like 250-400 ? I think because they are serving multiple users at the same time and it uses too much resources. But what if someone made a server that is only feeding one user with 1000 bots ??

**Comment by WJKH** [comment]
OMG, here we go again and again...
People want 1k bots when each server allow 220-250 players.
If you need more than 100 bots to get some decent mass, goto play parchis.

**Comment by WJKH** [comment]
BTW.. @Dohab you're getting 3 bots because you are using 1 IP, not 7.
If you don't setup a proxy server, forget it.

Also more IP doesn't mean more resources, add an IP to a VPS doesn't use any resource.

**Comment by Dohab** [comment]
@picusc I don't think that major bot sites are using proxies.
There must be an agreement between them and agar.io, it's business after all.
Because they can't depend on public proxies for there business, right? and what about fixing the scrambling after 24 hours, while our geniuses here scratching there heads for weeks? I believe they have the solution already, but they delay it 24 hours or so, so we think that they are good.
Anyways, using (NOPROXY) works great on my own server. If I can port  that to a FFA server, that would be amazing.

and @WJKH we will keep opening issues like this until we get a good answers. I've read almost all your replies in this repo, most of them are not productive. Everything you said is disappointing, you just keep us down, you tell us to do nothing, to think of nothing, to accept what we got, how are we gonna success like that, how are we stop thinking? and ... parchis? man ...

Speaking of productivity, you said:

> If you don't setup a proxy server, forget it. 

I've setup a proxy server using squid, and i've followed a tutorial to add all 7 IPs I've got, how to use them now?

> Also more IP doesn't mean more resources, add an IP to a VPS doesn't use any resource.

another dead end reply. no solution, no reasons, nothing .. just a plain "forget about it" phrase.

**Comment by picusc** [comment]
I don't think Agario and Bots sites have an alliance.

This is because when the last major update happened(10-11 days ago), it took Raga less than 48 hours to get their bots working but Agarbots.net took almost an entire week. 

But this time agarbots.net has already fixed their bots but raga hasn't been able to do it. Also, there are other sites too like agarbots.ovh and bagar.io who are working at their own pace. 

Also, check out [this interesting thread](https://github.com/davidmann4/ogar-feeder-bot/issues/56).

**Comment by DeepSnowNeeL** [comment]
Well at agarbot.ovh, I was in holidays when they published the first patch
so I couldn't react that fast. I can assure you, we are not related at all
with agar.io.

**Comment by WJKH** [comment]
@Dohab everyone will keep laughing when read 1k proxy / 3k bots.
It's not about how productive are my replies, you make the wrong questions then you get wrong answer.

> I've setup a proxy server using squid, and i've followed a tutorial to add all 7 IPs I've got, how to use them now?

Do you checked your proxy in a common browser?
Is your proxy working?

> another dead end reply. no solution, no reasons, nothing .. just a plain "forget about it" phrase.

Did you try to add 256 IP to a VPS to say it's not possible?
Now you can guess why you get wrong answer.

**Comment by Dohab** [comment]
@WJKH I didn't ask for magic, raga, agarbot and others have done it. I don't have any problem thinking that they may have contacted an alien hacker to help them, except that there is no proof of aliens existence, rather than using 1k proxies. Poetry saying: "Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.", and "If you don't make mistakes, you don't make anything".
Now I can focus on something other than proxies, it's the famous Edward Thorndike way, learn by trying and failing.
If you know something, why don't you share it? tell us what's wrong and whats right. I dare anyone ask the same question again if they get a detailed answers. no body laugh on no body.

**Comment by WJKH** [comment]
@Dohab

First, you understand me wrong. I was talking about running 1k bots for personal use (a game with 1k bots inside to be right), no for commercial use like as the sites you mention above.

Second, those sites were developed by programmers or the owner hired a programmer to develop it. You don't need an alien, just hire someone and you could get the same :)

Third, it's not a forum where you come for help or something like it. You can open an issue to report a problem, request a feature or something relevant to the project and I believe that if you don't know how configure your proxy server isn't relevant for the project.

Now if you still want to continue and try to be helped, you need tell us the problem because "I can't get more than 3 bots" does not say much and you speak too much but didn't reply my last questions.

**Comment by Dohab** [comment]
@WJKH lol, I do speak too much, maybe because I miss my wife.
Ok, you are right, I'm sorry, this is not a forum, my mistake, but there is no other place to ask.
Anyway, the answer to your questions, when I telnet my ips I get something like:
`HTTP/1.0 400 Bad Request
Server: squid/3.1.23
Mime-Version: 1.0
Date: Tue, 01 Mar 2016 05:45:33 GMT
Content-Type: text/html
Content-Length: 3661
X-Squid-Error: ERR_INVALID_REQ 0
Vary: Accept-Language
Content-Language: en
X-Cache: MISS from server.xxx.net
X-Cache-Lookup: NONE from server.xxx.net:3128
Via: 1.0 server.xxx.net (squid/3.1.23)
Connection: close`
and what seems to be a html code is printed beneath that.
When I enter my IP:PORT in chrome, I get an error page from my server, notice the last line;

```
`The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: /

Invalid URL

Some aspect of the requested URL is incorrect.

Some possible problems are:

Missing or incorrect access protocol (should be http:// or similar)

Missing hostname

Illegal double-escape in the URL-Path

Illegal character in hostname; underscores are not allowed.

Your cache administrator is root.


**Generated Tue, 01 Mar 2016 05:49:04 GMT by server.xxx.net (squid/3.1.23)**`
```

, And for adding 256 ips to my VPS, no I didn't try, but you told me once that adding ips to a vps doesn't make them act as proxies and my VPS count as one ip.

I'm sorry again, and if you suggest a place where people are talking about this repo in depth, that would be great.

**Comment by Dohab** [comment]
You know what? I think I'm gonna forget the hole thing and play fair, it's more fun without cheating.
Thanks all.
