### ISSUE TITLE
How to get more fb bots

### ISSUE THREAD

**Issue by ravyn120** [davidmann4/ogar-feeder-bot#430]
im using 20 fb cookies there's no token error but I only get 1 fb bot

**Comment by CupidStunts** [comment]
you need private/premium socks proxys

**Comment by hassanila** [comment]
No... OMG thats not the problem at all.. wtf...  ppl stop telling ppl what to do without knowledge. Its not cuz of proxies.. at all. Understand it.   The problem is the code.. it has to be refractored and edited to use fb tokens smartly. Thats why you get 1 fb bot

**Comment by ElieeCh** [comment]
xD

**Comment by hassanila** [comment]
Check out my bots... Im also using around 10 FB  but I dont get many mass bots    thats because if one connection fails you need to reuse that token to connect another one...   here: https://www.youtube.com/watch?v=qbXRaMiQQ7I

**Comment by CupidStunts** [comment]
@hassanila97 im using around 15 FB bots and i get most of them. if a proxy is dead or disconnects then so does it. your saying you need to do this & that but not telling anyone anything lol. there not even your bots either according to your vid..they belong to SrNicolas. if your not going to help then why comment? to show off or rub in peoples faces? the proxy needs a good 200 response in order to connect & a decent onboard timer in config.js....thats what im doing & its working ok,,,so unless your going to help? why bother commenting?

**Comment by CupidStunts** [comment]
oh and btw this community sucks balls lol... yall want something from what should be an opensource community. whatever happened to sharing is caring huh..id like to thank its levvie tho. if he never posted the new co-ords everyone would have nothing lol :)

**Comment by ravyn120** [comment]
Oh thanks that helps I'll fix my bots later @hassanila97

**Comment by ravyn120** [comment]
I'll add re trying tokens to my script

**Comment by hassanila** [comment]
@CupidStunts Yes.. those are SrNicolas bots.. but I got the code and completely remade it to be perfect :)..   sry  but I just get angry when I read something completely off the road   LOL :D    New bot amount record 350 bots  check it out:  https://youtu.be/Wq2CcKMdQGs
