### ISSUE TITLE
Flashing agario while using script

### ISSUE THREAD

**Issue by KingMatt123** [davidmann4/ogar-feeder-bot#70]
My agario flashes when I'm playing with the userscript

**Comment by davidbigglehorn1995** [comment]
change this
 // @run-at       document-body

to this

// @run-at       document-start

and remove this:

document.body.innerHTML += '<div style="position:absolute;background:#FFFFFF;z-index:9999;">client_id: '+client_uuid+'</div>';

**Comment by zeliad-papa** [comment]
Thanks

**Comment by ghost** [comment]
np

**Comment by WJKH** [comment]
No working, also give lots of errors at console.

**Comment by SimonyanG** [comment]
Changing to 
// @run-at document-start

and removing 
document.body.innerHTML(etc...

not helping
a lot of errors in console

**Comment by davidbigglehorn1995** [comment]
Here's my script: http://pastebin.com/tP4gqghM

Nothing special, it works though.

scroll to the bottom to edit the code

**Comment by zeliad-papa** [comment]
@davidbigglehorn1995 

I tried Now your script
I have this problem as #69

In Server.js I can not get the game server's IP (before your script does receive)

**Comment by davidmann4** [comment]
@davidbigglehorn1995 please contribute a pull request for this

**Comment by davidbigglehorn1995** [comment]
@davidmann4 i know not how
 Kunt u dit doen?

**Comment by zeliad-papa** [comment]
@davidbigglehorn1995 
https://github.com/davidmann4/agario-feeder-bot/compare

**Comment by zeliad-papa** [comment]
Now do what you said again
The problem at the moment Server.js not send to Feeder.js game server IP just like the #69 issue 
I do not get like this:

```
 { name: 'connect_server', ip: 'ws://151.80.98.53:1526' } 
```

(after editing I do only "save")
I got a browser error:

```
Uncaught TypeError: Can not read property 'ws' of undefinedtransmit_game_server_if_changed @ VM4045: 91 (anonymous function) @ VM4045: 70
50VM4045: 51 Uncaught TypeError: Can not read property 'drawScale' of undefined
```

(Do not know if this is related)

**Comment by zeliad-papa** [comment]
#74  :-1:

**Comment by davidmann4** [comment]
if someone could fix this it would be cool

**Comment by xzfc** [comment]
The problem is that expose inside your script is running at `document-body`, but it should be running at `document-start`. Another problem is that `$` and `document.body.innerHTML` can not be used at `document-start`, so that's why #74 does not work.

So, there are two ways of fixing it:
1. Use expose as separate userscript that runs at `document-start` while your bot script remains at `document-body`.
2. If you wanna expose code to be inlined in your bot script, then make it running at `document-start`, and make it use things only after they will appear (e.g. just put bot code inside `window.setTimeout`).

**Comment by davidmann4** [comment]
fixed
